"""Remove Like table temporarily

Revision ID: c4a47ca2f384
Revises: 0bc8b2c2a95a
Create Date: 2025-02-01 01:40:20.849040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a47ca2f384'
down_revision: Union[str, None] = '0bc8b2c2a95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
